STAT_LIST = [
    "Earth",
    "Air",
    "Fire",
    "Water",
]

PLAYERS = {
    "Bernard": {
        "earth": 188,
        "air": 141,
        "fire": 110,
        "water": 110,
        "arm": 105,
        "marm": 57,
        "init": 3,
    },
    "Dio": {
        "earth": 130,
        "air": 130,
        "fire": 170,
        "water": 130,
        "arm": 91,
        "marm": 95,
        "init": 3,
    },
    "Nyssa": {
        "earth": 110,
        "air": 200,
        "fire": 110,
        "water": 125,
        "arm": 57,
        "marm": 48,
        "init": 3,
    },
}


MONSTERS = {
    "Remedia": {
        "level": 60,
        "class": "caster",
        "importance": "boss",
        "elements": [],
        "fire": 160,
        "water": 160,
        "air": 140,
        "earth": 140,
        "hp": 3903,
        "mp": 2361,
        "arm": 40,
        "marm": 161,
        "dmg_multiplier": 21,
        "init": 5,
        "attack_difficulty": 20,
        "dmg_earth": 294,
        "dmg_air": 294,
        "dmg_fire": 336,
        "dmg_water": 336,
        "attacks": {
            "Light attack": {
                "name": "Basic Air",
                "offensive stat": "air",
                "defensive stat": "air",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "cut",
                "slow": 0,
                "mp": 0,
            },
            "Strong attack": {
                "name": "Basic Earth",
                "offensive stat": "earth",
                "defensive stat": "earth",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "cut",
                "slow": 0,
                "mp": 0,
            },
            "Magic": {
                "name": "Magic",
                "offensive stat": "fire",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "light",
                "slow": 0,
                "mp": 0,
            },
            "Control": {
                "name": "Control",
                "offensive stat": "water",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "light",
                "slow": 0,
                "mp": 0,
            },
        },
    },
    "Li-Grim": {
        "level": 70,
        "class": "caster",
        "importance": "boss",
        "elements": [{"light": "weak"}, {"shadow": "resist"}],
        "fire": 190,
        "water": 190,
        "air": 160,
        "earth": 160,
        "hp": 6531,
        "mp": 3021,
        "arm": 58,
        "marm": 235,
        "dmg_multiplier": 25,
        "init": 5,
        "attack_difficulty": 20,
        "dmg_earth": 400,
        "dmg_air": 400,
        "dmg_fire": 475,
        "dmg_water": 475,
        "attacks": {
            "Light attack": {
                "name": "Basic Air",
                "offensive stat": "air",
                "defensive stat": "air",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "shadow",
                "slow": 0,
                "mp": 0,
            },
            "Strong attack": {
                "name": "Basic Earth",
                "offensive stat": "earth",
                "defensive stat": "earth",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "shadow",
                "slow": 0,
                "mp": 0,
            },
            "Magic": {
                "name": "Magic",
                "offensive stat": "fire",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "shadow",
                "slow": 0,
                "mp": 0,
            },
            "Control": {
                "name": "Control",
                "offensive stat": "water",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "shadow",
                "slow": 0,
                "mp": 0,
            },
        },
    },
    "Juiz": {
        "level": 50,
        "class": "brute",
        "importance": "elite",
        "elements": [{"light": "resist"}, {"shadow": "weak"}],
        "earth": 140,
        "air": 140,
        "water": 110,
        "fire": 110,
        "hp": 2877,
        "mp": 477,
        "arm": 110,
        "marm": 27,
        "dmg_multiplier": 15,
        "init": 4,
        "attack_difficulty": 30,
        "dmg_earth": 210,
        "dmg_air": 210,
        "dmg_fire": 165,
        "dmg_water": 165,
        "attacks": {
            "Light attack": {
                "name": "Basic Air",
                "offensive stat": "air",
                "defensive stat": "air",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "cut",
                "slow": 0,
                "mp": 0,
            },
            "Strong attack": {
                "name": "Basic Earth",
                "offensive stat": "earth",
                "defensive stat": "earth",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "cut",
                "slow": 0,
                "mp": 0,
            },
            "Magic": {
                "name": "Magic",
                "offensive stat": "fire",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "light",
                "slow": 0,
                "mp": 0,
            },
            "Control": {
                "name": "Control",
                "offensive stat": "water",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "light",
                "slow": 0,
                "mp": 0,
            },
        },
    },
    "Leonardo": {
        "level": 56,
        "class": "quick",
        "importance": "elite",
        "elements": [{"light": "resist"}, {"shadow": "weak"}],
        "air": 150,
        "earth": 150,
        "water": 130,
        "fire": 130,
        "hp": 2230,
        "mp": 434,
        "arm": 23,
        "marm": 23,
        "dmg_multiplier": 15,
        "init": 4,
        "attack_difficulty": 30,
        "dmg_earth": 225,
        "dmg_air": 225,
        "dmg_fire": 195,
        "dmg_water": 195,
        "attacks": {
            "Light attack": {
                "name": "Basic Air",
                "offensive stat": "air",
                "defensive stat": "air",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "cut",
                "slow": 0,
                "mp": 0,
            },
            "Strong attack": {
                "name": "Basic Earth",
                "offensive stat": "earth",
                "defensive stat": "earth",
                "type": "physical",
                "range": 1,
                "extra difficulty": 0,
                "element": "cut",
                "slow": 0,
                "mp": 0,
            },
            "Magic": {
                "name": "Magic",
                "offensive stat": "fire",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "light",
                "slow": 0,
                "mp": 0,
            },
            "Control": {
                "name": "Control",
                "offensive stat": "water",
                "defensive stat": "water",
                "type": "magical",
                "range": 1,
                "extra difficulty": 0,
                "element": "light",
                "slow": 0,
                "mp": 0,
            },
        },
    },
}

ELEMENT_LIST = [
    "Crush",
    "Puncture",
    "Cut",
    "Fire",
    "Ice",
    "Lightning",
    "Air",
    "Earth",
    "Water",
    "Bio",
    "Light",
    "Shadow",
]


ATTACK_TYPE_LIST = ["Physical", "Magical"]

# Mental: Berserk, Charm, Confuse, Sleep
# Illusion: Blink, Vanish
# Seal: Blind, Disable, Immobilize, Mute
# Fatal: Condemn, Death, Gravity
# Elemental: Vulnerable: (Element), Resist: (Element), Immune: (Element), Absorb: (Element)
# Weaken: Curse, Meltdown, Weaken: [Armor, Magic, Mental, Physical, Speed]
# Strengthen: Regen, Strengthen: [Armor, Magic, Mental, Physical, Speed]
# Flight: Float, Flight
# Time: Slow, Stop, Haste, Premonition
# Toxic: Poison, Virus
# Barrier: Protect, Shell, Reflect, Reraise, Wall
# Transform: Stone, Toad, Zombie

LAWS = {
    "Action": [
        "Flanquear",
        "Bater De Frente",
        "Reações",
        "!Item",
        "!Flee",
        "Atacar fora do range",
        "Atacar mais que 4 quadrados",
        "Zone of control",
        "multiplos alvos",
        "alvo próprio",
        "curar hp",
        "repetir última ação",
    ],
    "Element": ELEMENT_LIST,
    "Weapon": [
        "Light Swords / Knives",
        "Weapons & Shields",
        "Heavy Weapons",
        "Polearms",
        "Claws / Gloves",
        "Katanas",
        "Bows",
        "Throwing Weapons",
        "Rifles / Crossbows",
        "Wands",
        "Staves",
        "Instruments",
        "Twin Blades",
    ],
    "Status": [
        "Mental",
        "Illusion",
        "Seal",
        "Fatal",
        "Elemental",
        "Weaken",
        "Strengthen",
        "Flight",
        "Time",
        "Toxic",
        "Barrier",
        "Transform",
    ],
}
